services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    env_file:
      - app.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --access-logfile - --error-logfile - --reload roadstone_project.wsgi
    # command: gunicorn --bind 0.0.0.0:8000 --access-logfile - --error-logfile - --reload -k uvicorn.workers.UvicornWorker roadstone_project.asgi
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - app.env

  celery:
    build: .
    command: celery -A roadstone_project worker --loglevel=info
    env_file:
      - app.env

volumes:
  postgres_data:
